// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calendarpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalendarServiceClient is the client API for CalendarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalendarServiceClient interface {
	// Получение свободных слотов в указанном интервале.
	ListFreeSlots(ctx context.Context, in *ListFreeSlotsRequest, opts ...grpc.CallOption) (*ListFreeSlotsResponse, error)
	// Алиас под ТЗ: GetAvailableSlots.
	GetAvailableSlots(ctx context.Context, in *ListFreeSlotsRequest, opts ...grpc.CallOption) (*ListFreeSlotsResponse, error)
	// Создание бронирования на свободный слот.
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error)
	// Алиас под ТЗ: BookSlot.
	BookSlot(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error)
	// Получение информации о бронировании.
	GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*GetBookingResponse, error)
	// Отмена ранее созданного бронирования.
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error)
	// Подтверждение бронирования (из ожидания в confirmed).
	ConfirmBooking(ctx context.Context, in *ConfirmBookingRequest, opts ...grpc.CallOption) (*ConfirmBookingResponse, error)
	// Проверка доступности слота.
	CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error)
	// Развёртывание расписания в окне.
	ExpandSchedule(ctx context.Context, in *ExpandScheduleRequest, opts ...grpc.CallOption) (*ExpandScheduleResponse, error)
	// Валидация слота.
	ValidateSlot(ctx context.Context, in *ValidateSlotRequest, opts ...grpc.CallOption) (*ValidateSlotResponse, error)
	// Быстрые предикаты для бота.
	GetNearestFreeSlot(ctx context.Context, in *GetNearestFreeSlotRequest, opts ...grpc.CallOption) (*GetNearestFreeSlotResponse, error)
	// Следующий свободный слот заданного провайдера от времени from (ограниченный until).
	GetNextProviderSlot(ctx context.Context, in *GetNextProviderSlotRequest, opts ...grpc.CallOption) (*GetNextProviderSlotResponse, error)
	// Маленькая выдача свободных слотов в интервале без пагинации (для быстрых подсказок).
	FindFreeSlots(ctx context.Context, in *FindFreeSlotsRequest, opts ...grpc.CallOption) (*FindFreeSlotsResponse, error)
	// Список бронирований клиента за период.
	ListBookings(ctx context.Context, in *ListBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error)
	// Список бронирований провайдера за период.
	ListProviderBookings(ctx context.Context, in *ListProviderBookingsRequest, opts ...grpc.CallOption) (*ListProviderBookingsResponse, error)
	// Получение расписаний провайдера (повторяющиеся правила).
	ListProviderSchedules(ctx context.Context, in *ListProviderSchedulesRequest, opts ...grpc.CallOption) (*ListProviderSchedulesResponse, error)
	// CRUD расписаний провайдера.
	CreateProviderSchedule(ctx context.Context, in *CreateProviderScheduleRequest, opts ...grpc.CallOption) (*CreateProviderScheduleResponse, error)
	// Обновление расписания провайдера по ID.
	UpdateProviderSchedule(ctx context.Context, in *UpdateProviderScheduleRequest, opts ...grpc.CallOption) (*UpdateProviderScheduleResponse, error)
	// Удаление расписания провайдера по ID.
	DeleteProviderSchedule(ctx context.Context, in *DeleteProviderScheduleRequest, opts ...grpc.CallOption) (*DeleteProviderScheduleResponse, error)
	// Массовая отмена слотов провайдера в интервале (возвращает список затронутых бронирований).
	BulkCancelProviderSlots(ctx context.Context, in *BulkCancelProviderSlotsRequest, opts ...grpc.CallOption) (*BulkCancelProviderSlotsResponse, error)
	// CRUD слотов.
	CreateSlot(ctx context.Context, in *CreateSlotRequest, opts ...grpc.CallOption) (*CreateSlotResponse, error)
	// Обновление слота по ID.
	UpdateSlot(ctx context.Context, in *UpdateSlotRequest, opts ...grpc.CallOption) (*UpdateSlotResponse, error)
	// Удаление слота по ID.
	DeleteSlot(ctx context.Context, in *DeleteSlotRequest, opts ...grpc.CallOption) (*DeleteSlotResponse, error)
	// Список слотов провайдера (со статусами и бронями).
	ListProviderSlots(ctx context.Context, in *ListProviderSlotsRequest, opts ...grpc.CallOption) (*ListProviderSlotsResponse, error)
	// Публичный каталог услуг.
	ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error)
	// Создание услуги.
	CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error)
	// Публичный список провайдеров (опционально отфильтрованный по услуге).
	ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error)
	// Публичный профиль провайдера + его услуги.
	ListProviderServices(ctx context.Context, in *ListProviderServicesRequest, opts ...grpc.CallOption) (*ListProviderServicesResponse, error)
	// Установить список услуг провайдера (заменить связи provider_services).
	SetProviderServices(ctx context.Context, in *SetProviderServicesRequest, opts ...grpc.CallOption) (*SetProviderServicesResponse, error)
	// Обновление профиля провайдера.
	UpdateProviderProfile(ctx context.Context, in *UpdateProviderProfileRequest, opts ...grpc.CallOption) (*UpdateProviderProfileResponse, error)
}

type calendarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarServiceClient(cc grpc.ClientConnInterface) CalendarServiceClient {
	return &calendarServiceClient{cc}
}

func (c *calendarServiceClient) ListFreeSlots(ctx context.Context, in *ListFreeSlotsRequest, opts ...grpc.CallOption) (*ListFreeSlotsResponse, error) {
	out := new(ListFreeSlotsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListFreeSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) GetAvailableSlots(ctx context.Context, in *ListFreeSlotsRequest, opts ...grpc.CallOption) (*ListFreeSlotsResponse, error) {
	out := new(ListFreeSlotsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/GetAvailableSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error) {
	out := new(CreateBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CreateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) BookSlot(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error) {
	out := new(CreateBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/BookSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*GetBookingResponse, error) {
	out := new(GetBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/GetBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error) {
	out := new(CancelBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CancelBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ConfirmBooking(ctx context.Context, in *ConfirmBookingRequest, opts ...grpc.CallOption) (*ConfirmBookingResponse, error) {
	out := new(ConfirmBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ConfirmBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CheckAvailability(ctx context.Context, in *CheckAvailabilityRequest, opts ...grpc.CallOption) (*CheckAvailabilityResponse, error) {
	out := new(CheckAvailabilityResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CheckAvailability", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ExpandSchedule(ctx context.Context, in *ExpandScheduleRequest, opts ...grpc.CallOption) (*ExpandScheduleResponse, error) {
	out := new(ExpandScheduleResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ExpandSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ValidateSlot(ctx context.Context, in *ValidateSlotRequest, opts ...grpc.CallOption) (*ValidateSlotResponse, error) {
	out := new(ValidateSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ValidateSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) GetNearestFreeSlot(ctx context.Context, in *GetNearestFreeSlotRequest, opts ...grpc.CallOption) (*GetNearestFreeSlotResponse, error) {
	out := new(GetNearestFreeSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/GetNearestFreeSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) GetNextProviderSlot(ctx context.Context, in *GetNextProviderSlotRequest, opts ...grpc.CallOption) (*GetNextProviderSlotResponse, error) {
	out := new(GetNextProviderSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/GetNextProviderSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) FindFreeSlots(ctx context.Context, in *FindFreeSlotsRequest, opts ...grpc.CallOption) (*FindFreeSlotsResponse, error) {
	out := new(FindFreeSlotsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/FindFreeSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListBookings(ctx context.Context, in *ListBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error) {
	out := new(ListBookingsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListProviderBookings(ctx context.Context, in *ListProviderBookingsRequest, opts ...grpc.CallOption) (*ListProviderBookingsResponse, error) {
	out := new(ListProviderBookingsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListProviderBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListProviderSchedules(ctx context.Context, in *ListProviderSchedulesRequest, opts ...grpc.CallOption) (*ListProviderSchedulesResponse, error) {
	out := new(ListProviderSchedulesResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListProviderSchedules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CreateProviderSchedule(ctx context.Context, in *CreateProviderScheduleRequest, opts ...grpc.CallOption) (*CreateProviderScheduleResponse, error) {
	out := new(CreateProviderScheduleResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CreateProviderSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) UpdateProviderSchedule(ctx context.Context, in *UpdateProviderScheduleRequest, opts ...grpc.CallOption) (*UpdateProviderScheduleResponse, error) {
	out := new(UpdateProviderScheduleResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/UpdateProviderSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) DeleteProviderSchedule(ctx context.Context, in *DeleteProviderScheduleRequest, opts ...grpc.CallOption) (*DeleteProviderScheduleResponse, error) {
	out := new(DeleteProviderScheduleResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/DeleteProviderSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) BulkCancelProviderSlots(ctx context.Context, in *BulkCancelProviderSlotsRequest, opts ...grpc.CallOption) (*BulkCancelProviderSlotsResponse, error) {
	out := new(BulkCancelProviderSlotsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/BulkCancelProviderSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CreateSlot(ctx context.Context, in *CreateSlotRequest, opts ...grpc.CallOption) (*CreateSlotResponse, error) {
	out := new(CreateSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CreateSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) UpdateSlot(ctx context.Context, in *UpdateSlotRequest, opts ...grpc.CallOption) (*UpdateSlotResponse, error) {
	out := new(UpdateSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/UpdateSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) DeleteSlot(ctx context.Context, in *DeleteSlotRequest, opts ...grpc.CallOption) (*DeleteSlotResponse, error) {
	out := new(DeleteSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/DeleteSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListProviderSlots(ctx context.Context, in *ListProviderSlotsRequest, opts ...grpc.CallOption) (*ListProviderSlotsResponse, error) {
	out := new(ListProviderSlotsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListProviderSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListServices(ctx context.Context, in *ListServicesRequest, opts ...grpc.CallOption) (*ListServicesResponse, error) {
	out := new(ListServicesResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CreateService(ctx context.Context, in *CreateServiceRequest, opts ...grpc.CallOption) (*CreateServiceResponse, error) {
	out := new(CreateServiceResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CreateService", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListProviders(ctx context.Context, in *ListProvidersRequest, opts ...grpc.CallOption) (*ListProvidersResponse, error) {
	out := new(ListProvidersResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListProviders", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListProviderServices(ctx context.Context, in *ListProviderServicesRequest, opts ...grpc.CallOption) (*ListProviderServicesResponse, error) {
	out := new(ListProviderServicesResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListProviderServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) SetProviderServices(ctx context.Context, in *SetProviderServicesRequest, opts ...grpc.CallOption) (*SetProviderServicesResponse, error) {
	out := new(SetProviderServicesResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/SetProviderServices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) UpdateProviderProfile(ctx context.Context, in *UpdateProviderProfileRequest, opts ...grpc.CallOption) (*UpdateProviderProfileResponse, error) {
	out := new(UpdateProviderProfileResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/UpdateProviderProfile", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServiceServer is the server API for CalendarService service.
// All implementations must embed UnimplementedCalendarServiceServer
// for forward compatibility
type CalendarServiceServer interface {
	// Получение свободных слотов в указанном интервале.
	ListFreeSlots(context.Context, *ListFreeSlotsRequest) (*ListFreeSlotsResponse, error)
	// Алиас под ТЗ: GetAvailableSlots.
	GetAvailableSlots(context.Context, *ListFreeSlotsRequest) (*ListFreeSlotsResponse, error)
	// Создание бронирования на свободный слот.
	CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error)
	// Алиас под ТЗ: BookSlot.
	BookSlot(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error)
	// Получение информации о бронировании.
	GetBooking(context.Context, *GetBookingRequest) (*GetBookingResponse, error)
	// Отмена ранее созданного бронирования.
	CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error)
	// Подтверждение бронирования (из ожидания в confirmed).
	ConfirmBooking(context.Context, *ConfirmBookingRequest) (*ConfirmBookingResponse, error)
	// Проверка доступности слота.
	CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error)
	// Развёртывание расписания в окне.
	ExpandSchedule(context.Context, *ExpandScheduleRequest) (*ExpandScheduleResponse, error)
	// Валидация слота.
	ValidateSlot(context.Context, *ValidateSlotRequest) (*ValidateSlotResponse, error)
	// Быстрые предикаты для бота.
	GetNearestFreeSlot(context.Context, *GetNearestFreeSlotRequest) (*GetNearestFreeSlotResponse, error)
	// Следующий свободный слот заданного провайдера от времени from (ограниченный until).
	GetNextProviderSlot(context.Context, *GetNextProviderSlotRequest) (*GetNextProviderSlotResponse, error)
	// Маленькая выдача свободных слотов в интервале без пагинации (для быстрых подсказок).
	FindFreeSlots(context.Context, *FindFreeSlotsRequest) (*FindFreeSlotsResponse, error)
	// Список бронирований клиента за период.
	ListBookings(context.Context, *ListBookingsRequest) (*ListBookingsResponse, error)
	// Список бронирований провайдера за период.
	ListProviderBookings(context.Context, *ListProviderBookingsRequest) (*ListProviderBookingsResponse, error)
	// Получение расписаний провайдера (повторяющиеся правила).
	ListProviderSchedules(context.Context, *ListProviderSchedulesRequest) (*ListProviderSchedulesResponse, error)
	// CRUD расписаний провайдера.
	CreateProviderSchedule(context.Context, *CreateProviderScheduleRequest) (*CreateProviderScheduleResponse, error)
	// Обновление расписания провайдера по ID.
	UpdateProviderSchedule(context.Context, *UpdateProviderScheduleRequest) (*UpdateProviderScheduleResponse, error)
	// Удаление расписания провайдера по ID.
	DeleteProviderSchedule(context.Context, *DeleteProviderScheduleRequest) (*DeleteProviderScheduleResponse, error)
	// Массовая отмена слотов провайдера в интервале (возвращает список затронутых бронирований).
	BulkCancelProviderSlots(context.Context, *BulkCancelProviderSlotsRequest) (*BulkCancelProviderSlotsResponse, error)
	// CRUD слотов.
	CreateSlot(context.Context, *CreateSlotRequest) (*CreateSlotResponse, error)
	// Обновление слота по ID.
	UpdateSlot(context.Context, *UpdateSlotRequest) (*UpdateSlotResponse, error)
	// Удаление слота по ID.
	DeleteSlot(context.Context, *DeleteSlotRequest) (*DeleteSlotResponse, error)
	// Список слотов провайдера (со статусами и бронями).
	ListProviderSlots(context.Context, *ListProviderSlotsRequest) (*ListProviderSlotsResponse, error)
	// Публичный каталог услуг.
	ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error)
	// Создание услуги.
	CreateService(context.Context, *CreateServiceRequest) (*CreateServiceResponse, error)
	// Публичный список провайдеров (опционально отфильтрованный по услуге).
	ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error)
	// Публичный профиль провайдера + его услуги.
	ListProviderServices(context.Context, *ListProviderServicesRequest) (*ListProviderServicesResponse, error)
	// Установить список услуг провайдера (заменить связи provider_services).
	SetProviderServices(context.Context, *SetProviderServicesRequest) (*SetProviderServicesResponse, error)
	// Обновление профиля провайдера.
	UpdateProviderProfile(context.Context, *UpdateProviderProfileRequest) (*UpdateProviderProfileResponse, error)
	mustEmbedUnimplementedCalendarServiceServer()
}

// UnimplementedCalendarServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalendarServiceServer struct {
}

func (UnimplementedCalendarServiceServer) ListFreeSlots(context.Context, *ListFreeSlotsRequest) (*ListFreeSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFreeSlots not implemented")
}
func (UnimplementedCalendarServiceServer) GetAvailableSlots(context.Context, *ListFreeSlotsRequest) (*ListFreeSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAvailableSlots not implemented")
}
func (UnimplementedCalendarServiceServer) CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedCalendarServiceServer) BookSlot(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BookSlot not implemented")
}
func (UnimplementedCalendarServiceServer) GetBooking(context.Context, *GetBookingRequest) (*GetBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooking not implemented")
}
func (UnimplementedCalendarServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedCalendarServiceServer) ConfirmBooking(context.Context, *ConfirmBookingRequest) (*ConfirmBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmBooking not implemented")
}
func (UnimplementedCalendarServiceServer) CheckAvailability(context.Context, *CheckAvailabilityRequest) (*CheckAvailabilityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAvailability not implemented")
}
func (UnimplementedCalendarServiceServer) ExpandSchedule(context.Context, *ExpandScheduleRequest) (*ExpandScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExpandSchedule not implemented")
}
func (UnimplementedCalendarServiceServer) ValidateSlot(context.Context, *ValidateSlotRequest) (*ValidateSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSlot not implemented")
}
func (UnimplementedCalendarServiceServer) GetNearestFreeSlot(context.Context, *GetNearestFreeSlotRequest) (*GetNearestFreeSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNearestFreeSlot not implemented")
}
func (UnimplementedCalendarServiceServer) GetNextProviderSlot(context.Context, *GetNextProviderSlotRequest) (*GetNextProviderSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNextProviderSlot not implemented")
}
func (UnimplementedCalendarServiceServer) FindFreeSlots(context.Context, *FindFreeSlotsRequest) (*FindFreeSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindFreeSlots not implemented")
}
func (UnimplementedCalendarServiceServer) ListBookings(context.Context, *ListBookingsRequest) (*ListBookingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBookings not implemented")
}
func (UnimplementedCalendarServiceServer) ListProviderBookings(context.Context, *ListProviderBookingsRequest) (*ListProviderBookingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviderBookings not implemented")
}
func (UnimplementedCalendarServiceServer) ListProviderSchedules(context.Context, *ListProviderSchedulesRequest) (*ListProviderSchedulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviderSchedules not implemented")
}
func (UnimplementedCalendarServiceServer) CreateProviderSchedule(context.Context, *CreateProviderScheduleRequest) (*CreateProviderScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProviderSchedule not implemented")
}
func (UnimplementedCalendarServiceServer) UpdateProviderSchedule(context.Context, *UpdateProviderScheduleRequest) (*UpdateProviderScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProviderSchedule not implemented")
}
func (UnimplementedCalendarServiceServer) DeleteProviderSchedule(context.Context, *DeleteProviderScheduleRequest) (*DeleteProviderScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProviderSchedule not implemented")
}
func (UnimplementedCalendarServiceServer) BulkCancelProviderSlots(context.Context, *BulkCancelProviderSlotsRequest) (*BulkCancelProviderSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BulkCancelProviderSlots not implemented")
}
func (UnimplementedCalendarServiceServer) CreateSlot(context.Context, *CreateSlotRequest) (*CreateSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSlot not implemented")
}
func (UnimplementedCalendarServiceServer) UpdateSlot(context.Context, *UpdateSlotRequest) (*UpdateSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSlot not implemented")
}
func (UnimplementedCalendarServiceServer) DeleteSlot(context.Context, *DeleteSlotRequest) (*DeleteSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSlot not implemented")
}
func (UnimplementedCalendarServiceServer) ListProviderSlots(context.Context, *ListProviderSlotsRequest) (*ListProviderSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviderSlots not implemented")
}
func (UnimplementedCalendarServiceServer) ListServices(context.Context, *ListServicesRequest) (*ListServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListServices not implemented")
}
func (UnimplementedCalendarServiceServer) CreateService(context.Context, *CreateServiceRequest) (*CreateServiceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateService not implemented")
}
func (UnimplementedCalendarServiceServer) ListProviders(context.Context, *ListProvidersRequest) (*ListProvidersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviders not implemented")
}
func (UnimplementedCalendarServiceServer) ListProviderServices(context.Context, *ListProviderServicesRequest) (*ListProviderServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviderServices not implemented")
}
func (UnimplementedCalendarServiceServer) SetProviderServices(context.Context, *SetProviderServicesRequest) (*SetProviderServicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetProviderServices not implemented")
}
func (UnimplementedCalendarServiceServer) UpdateProviderProfile(context.Context, *UpdateProviderProfileRequest) (*UpdateProviderProfileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProviderProfile not implemented")
}
func (UnimplementedCalendarServiceServer) mustEmbedUnimplementedCalendarServiceServer() {}

// UnsafeCalendarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarServiceServer will
// result in compilation errors.
type UnsafeCalendarServiceServer interface {
	mustEmbedUnimplementedCalendarServiceServer()
}

func RegisterCalendarServiceServer(s grpc.ServiceRegistrar, srv CalendarServiceServer) {
	s.RegisterService(&CalendarService_ServiceDesc, srv)
}

func _CalendarService_ListFreeSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFreeSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListFreeSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListFreeSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListFreeSlots(ctx, req.(*ListFreeSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_GetAvailableSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFreeSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GetAvailableSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/GetAvailableSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GetAvailableSlots(ctx, req.(*ListFreeSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_BookSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).BookSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/BookSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).BookSlot(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_GetBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GetBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/GetBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GetBooking(ctx, req.(*GetBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CancelBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ConfirmBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ConfirmBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ConfirmBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ConfirmBooking(ctx, req.(*ConfirmBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CheckAvailability_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAvailabilityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CheckAvailability(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CheckAvailability",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CheckAvailability(ctx, req.(*CheckAvailabilityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ExpandSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpandScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ExpandSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ExpandSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ExpandSchedule(ctx, req.(*ExpandScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ValidateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ValidateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ValidateSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ValidateSlot(ctx, req.(*ValidateSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_GetNearestFreeSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNearestFreeSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GetNearestFreeSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/GetNearestFreeSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GetNearestFreeSlot(ctx, req.(*GetNearestFreeSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_GetNextProviderSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNextProviderSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GetNextProviderSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/GetNextProviderSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GetNextProviderSlot(ctx, req.(*GetNextProviderSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_FindFreeSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindFreeSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).FindFreeSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/FindFreeSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).FindFreeSlots(ctx, req.(*FindFreeSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListBookings(ctx, req.(*ListBookingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListProviderBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderBookingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListProviderBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListProviderBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListProviderBookings(ctx, req.(*ListProviderBookingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListProviderSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListProviderSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListProviderSchedules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListProviderSchedules(ctx, req.(*ListProviderSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CreateProviderSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateProviderSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CreateProviderSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateProviderSchedule(ctx, req.(*CreateProviderScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_UpdateProviderSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).UpdateProviderSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/UpdateProviderSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).UpdateProviderSchedule(ctx, req.(*UpdateProviderScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_DeleteProviderSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).DeleteProviderSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/DeleteProviderSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).DeleteProviderSchedule(ctx, req.(*DeleteProviderScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_BulkCancelProviderSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BulkCancelProviderSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).BulkCancelProviderSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/BulkCancelProviderSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).BulkCancelProviderSlots(ctx, req.(*BulkCancelProviderSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CreateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CreateSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateSlot(ctx, req.(*CreateSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_UpdateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).UpdateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/UpdateSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).UpdateSlot(ctx, req.(*UpdateSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_DeleteSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).DeleteSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/DeleteSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).DeleteSlot(ctx, req.(*DeleteSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListProviderSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListProviderSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListProviderSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListProviderSlots(ctx, req.(*ListProviderSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListServices(ctx, req.(*ListServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateServiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateService(ctx, req.(*CreateServiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListProviders_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProvidersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListProviders(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListProviders",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListProviders(ctx, req.(*ListProvidersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListProviderServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListProviderServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListProviderServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListProviderServices(ctx, req.(*ListProviderServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_SetProviderServices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetProviderServicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).SetProviderServices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/SetProviderServices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).SetProviderServices(ctx, req.(*SetProviderServicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_UpdateProviderProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderProfileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).UpdateProviderProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/UpdateProviderProfile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).UpdateProviderProfile(ctx, req.(*UpdateProviderProfileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalendarService_ServiceDesc is the grpc.ServiceDesc for CalendarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalendarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.v1.CalendarService",
	HandlerType: (*CalendarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFreeSlots",
			Handler:    _CalendarService_ListFreeSlots_Handler,
		},
		{
			MethodName: "GetAvailableSlots",
			Handler:    _CalendarService_GetAvailableSlots_Handler,
		},
		{
			MethodName: "CreateBooking",
			Handler:    _CalendarService_CreateBooking_Handler,
		},
		{
			MethodName: "BookSlot",
			Handler:    _CalendarService_BookSlot_Handler,
		},
		{
			MethodName: "GetBooking",
			Handler:    _CalendarService_GetBooking_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _CalendarService_CancelBooking_Handler,
		},
		{
			MethodName: "ConfirmBooking",
			Handler:    _CalendarService_ConfirmBooking_Handler,
		},
		{
			MethodName: "CheckAvailability",
			Handler:    _CalendarService_CheckAvailability_Handler,
		},
		{
			MethodName: "ExpandSchedule",
			Handler:    _CalendarService_ExpandSchedule_Handler,
		},
		{
			MethodName: "ValidateSlot",
			Handler:    _CalendarService_ValidateSlot_Handler,
		},
		{
			MethodName: "GetNearestFreeSlot",
			Handler:    _CalendarService_GetNearestFreeSlot_Handler,
		},
		{
			MethodName: "GetNextProviderSlot",
			Handler:    _CalendarService_GetNextProviderSlot_Handler,
		},
		{
			MethodName: "FindFreeSlots",
			Handler:    _CalendarService_FindFreeSlots_Handler,
		},
		{
			MethodName: "ListBookings",
			Handler:    _CalendarService_ListBookings_Handler,
		},
		{
			MethodName: "ListProviderBookings",
			Handler:    _CalendarService_ListProviderBookings_Handler,
		},
		{
			MethodName: "ListProviderSchedules",
			Handler:    _CalendarService_ListProviderSchedules_Handler,
		},
		{
			MethodName: "CreateProviderSchedule",
			Handler:    _CalendarService_CreateProviderSchedule_Handler,
		},
		{
			MethodName: "UpdateProviderSchedule",
			Handler:    _CalendarService_UpdateProviderSchedule_Handler,
		},
		{
			MethodName: "DeleteProviderSchedule",
			Handler:    _CalendarService_DeleteProviderSchedule_Handler,
		},
		{
			MethodName: "BulkCancelProviderSlots",
			Handler:    _CalendarService_BulkCancelProviderSlots_Handler,
		},
		{
			MethodName: "CreateSlot",
			Handler:    _CalendarService_CreateSlot_Handler,
		},
		{
			MethodName: "UpdateSlot",
			Handler:    _CalendarService_UpdateSlot_Handler,
		},
		{
			MethodName: "DeleteSlot",
			Handler:    _CalendarService_DeleteSlot_Handler,
		},
		{
			MethodName: "ListProviderSlots",
			Handler:    _CalendarService_ListProviderSlots_Handler,
		},
		{
			MethodName: "ListServices",
			Handler:    _CalendarService_ListServices_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _CalendarService_CreateService_Handler,
		},
		{
			MethodName: "ListProviders",
			Handler:    _CalendarService_ListProviders_Handler,
		},
		{
			MethodName: "ListProviderServices",
			Handler:    _CalendarService_ListProviderServices_Handler,
		},
		{
			MethodName: "SetProviderServices",
			Handler:    _CalendarService_SetProviderServices_Handler,
		},
		{
			MethodName: "UpdateProviderProfile",
			Handler:    _CalendarService_UpdateProviderProfile_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calendar/v1/calendar.proto",
}
