// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package calendarpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CalendarServiceClient is the client API for CalendarService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CalendarServiceClient interface {
	// Получение свободных слотов в указанном интервале.
	ListFreeSlots(ctx context.Context, in *ListFreeSlotsRequest, opts ...grpc.CallOption) (*ListFreeSlotsResponse, error)
	// Создание бронирования на свободный слот.
	CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error)
	// Получение информации о бронировании.
	GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*GetBookingResponse, error)
	// Отмена ранее созданного бронирования.
	CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error)
	// Список бронирований клиента за период.
	ListBookings(ctx context.Context, in *ListBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error)
	// Получение расписаний провайдера (повторяющиеся правила).
	ListProviderSchedules(ctx context.Context, in *ListProviderSchedulesRequest, opts ...grpc.CallOption) (*ListProviderSchedulesResponse, error)
	// CRUD расписаний провайдера.
	CreateProviderSchedule(ctx context.Context, in *CreateProviderScheduleRequest, opts ...grpc.CallOption) (*CreateProviderScheduleResponse, error)
	UpdateProviderSchedule(ctx context.Context, in *UpdateProviderScheduleRequest, opts ...grpc.CallOption) (*UpdateProviderScheduleResponse, error)
	DeleteProviderSchedule(ctx context.Context, in *DeleteProviderScheduleRequest, opts ...grpc.CallOption) (*DeleteProviderScheduleResponse, error)
	// CRUD слотов.
	CreateSlot(ctx context.Context, in *CreateSlotRequest, opts ...grpc.CallOption) (*CreateSlotResponse, error)
	UpdateSlot(ctx context.Context, in *UpdateSlotRequest, opts ...grpc.CallOption) (*UpdateSlotResponse, error)
	DeleteSlot(ctx context.Context, in *DeleteSlotRequest, opts ...grpc.CallOption) (*DeleteSlotResponse, error)
}

type calendarServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCalendarServiceClient(cc grpc.ClientConnInterface) CalendarServiceClient {
	return &calendarServiceClient{cc}
}

func (c *calendarServiceClient) ListFreeSlots(ctx context.Context, in *ListFreeSlotsRequest, opts ...grpc.CallOption) (*ListFreeSlotsResponse, error) {
	out := new(ListFreeSlotsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListFreeSlots", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CreateBooking(ctx context.Context, in *CreateBookingRequest, opts ...grpc.CallOption) (*CreateBookingResponse, error) {
	out := new(CreateBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CreateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) GetBooking(ctx context.Context, in *GetBookingRequest, opts ...grpc.CallOption) (*GetBookingResponse, error) {
	out := new(GetBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/GetBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CancelBooking(ctx context.Context, in *CancelBookingRequest, opts ...grpc.CallOption) (*CancelBookingResponse, error) {
	out := new(CancelBookingResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CancelBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListBookings(ctx context.Context, in *ListBookingsRequest, opts ...grpc.CallOption) (*ListBookingsResponse, error) {
	out := new(ListBookingsResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) ListProviderSchedules(ctx context.Context, in *ListProviderSchedulesRequest, opts ...grpc.CallOption) (*ListProviderSchedulesResponse, error) {
	out := new(ListProviderSchedulesResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/ListProviderSchedules", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CreateProviderSchedule(ctx context.Context, in *CreateProviderScheduleRequest, opts ...grpc.CallOption) (*CreateProviderScheduleResponse, error) {
	out := new(CreateProviderScheduleResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CreateProviderSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) UpdateProviderSchedule(ctx context.Context, in *UpdateProviderScheduleRequest, opts ...grpc.CallOption) (*UpdateProviderScheduleResponse, error) {
	out := new(UpdateProviderScheduleResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/UpdateProviderSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) DeleteProviderSchedule(ctx context.Context, in *DeleteProviderScheduleRequest, opts ...grpc.CallOption) (*DeleteProviderScheduleResponse, error) {
	out := new(DeleteProviderScheduleResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/DeleteProviderSchedule", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) CreateSlot(ctx context.Context, in *CreateSlotRequest, opts ...grpc.CallOption) (*CreateSlotResponse, error) {
	out := new(CreateSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/CreateSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) UpdateSlot(ctx context.Context, in *UpdateSlotRequest, opts ...grpc.CallOption) (*UpdateSlotResponse, error) {
	out := new(UpdateSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/UpdateSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *calendarServiceClient) DeleteSlot(ctx context.Context, in *DeleteSlotRequest, opts ...grpc.CallOption) (*DeleteSlotResponse, error) {
	out := new(DeleteSlotResponse)
	err := c.cc.Invoke(ctx, "/calendar.v1.CalendarService/DeleteSlot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalendarServiceServer is the server API for CalendarService service.
// All implementations must embed UnimplementedCalendarServiceServer
// for forward compatibility
type CalendarServiceServer interface {
	// Получение свободных слотов в указанном интервале.
	ListFreeSlots(context.Context, *ListFreeSlotsRequest) (*ListFreeSlotsResponse, error)
	// Создание бронирования на свободный слот.
	CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error)
	// Получение информации о бронировании.
	GetBooking(context.Context, *GetBookingRequest) (*GetBookingResponse, error)
	// Отмена ранее созданного бронирования.
	CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error)
	// Список бронирований клиента за период.
	ListBookings(context.Context, *ListBookingsRequest) (*ListBookingsResponse, error)
	// Получение расписаний провайдера (повторяющиеся правила).
	ListProviderSchedules(context.Context, *ListProviderSchedulesRequest) (*ListProviderSchedulesResponse, error)
	// CRUD расписаний провайдера.
	CreateProviderSchedule(context.Context, *CreateProviderScheduleRequest) (*CreateProviderScheduleResponse, error)
	UpdateProviderSchedule(context.Context, *UpdateProviderScheduleRequest) (*UpdateProviderScheduleResponse, error)
	DeleteProviderSchedule(context.Context, *DeleteProviderScheduleRequest) (*DeleteProviderScheduleResponse, error)
	// CRUD слотов.
	CreateSlot(context.Context, *CreateSlotRequest) (*CreateSlotResponse, error)
	UpdateSlot(context.Context, *UpdateSlotRequest) (*UpdateSlotResponse, error)
	DeleteSlot(context.Context, *DeleteSlotRequest) (*DeleteSlotResponse, error)
	mustEmbedUnimplementedCalendarServiceServer()
}

// UnimplementedCalendarServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCalendarServiceServer struct {
}

func (UnimplementedCalendarServiceServer) ListFreeSlots(context.Context, *ListFreeSlotsRequest) (*ListFreeSlotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListFreeSlots not implemented")
}
func (UnimplementedCalendarServiceServer) CreateBooking(context.Context, *CreateBookingRequest) (*CreateBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}
func (UnimplementedCalendarServiceServer) GetBooking(context.Context, *GetBookingRequest) (*GetBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBooking not implemented")
}
func (UnimplementedCalendarServiceServer) CancelBooking(context.Context, *CancelBookingRequest) (*CancelBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelBooking not implemented")
}
func (UnimplementedCalendarServiceServer) ListBookings(context.Context, *ListBookingsRequest) (*ListBookingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBookings not implemented")
}
func (UnimplementedCalendarServiceServer) ListProviderSchedules(context.Context, *ListProviderSchedulesRequest) (*ListProviderSchedulesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListProviderSchedules not implemented")
}
func (UnimplementedCalendarServiceServer) CreateProviderSchedule(context.Context, *CreateProviderScheduleRequest) (*CreateProviderScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateProviderSchedule not implemented")
}
func (UnimplementedCalendarServiceServer) UpdateProviderSchedule(context.Context, *UpdateProviderScheduleRequest) (*UpdateProviderScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateProviderSchedule not implemented")
}
func (UnimplementedCalendarServiceServer) DeleteProviderSchedule(context.Context, *DeleteProviderScheduleRequest) (*DeleteProviderScheduleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteProviderSchedule not implemented")
}
func (UnimplementedCalendarServiceServer) CreateSlot(context.Context, *CreateSlotRequest) (*CreateSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSlot not implemented")
}
func (UnimplementedCalendarServiceServer) UpdateSlot(context.Context, *UpdateSlotRequest) (*UpdateSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSlot not implemented")
}
func (UnimplementedCalendarServiceServer) DeleteSlot(context.Context, *DeleteSlotRequest) (*DeleteSlotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSlot not implemented")
}
func (UnimplementedCalendarServiceServer) mustEmbedUnimplementedCalendarServiceServer() {}

// UnsafeCalendarServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CalendarServiceServer will
// result in compilation errors.
type UnsafeCalendarServiceServer interface {
	mustEmbedUnimplementedCalendarServiceServer()
}

func RegisterCalendarServiceServer(s grpc.ServiceRegistrar, srv CalendarServiceServer) {
	s.RegisterService(&CalendarService_ServiceDesc, srv)
}

func _CalendarService_ListFreeSlots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListFreeSlotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListFreeSlots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListFreeSlots",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListFreeSlots(ctx, req.(*ListFreeSlotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateBooking(ctx, req.(*CreateBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_GetBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).GetBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/GetBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).GetBooking(ctx, req.(*GetBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CancelBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CancelBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CancelBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CancelBooking(ctx, req.(*CancelBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBookingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListBookings(ctx, req.(*ListBookingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_ListProviderSchedules_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListProviderSchedulesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).ListProviderSchedules(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/ListProviderSchedules",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).ListProviderSchedules(ctx, req.(*ListProviderSchedulesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CreateProviderSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateProviderScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateProviderSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CreateProviderSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateProviderSchedule(ctx, req.(*CreateProviderScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_UpdateProviderSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProviderScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).UpdateProviderSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/UpdateProviderSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).UpdateProviderSchedule(ctx, req.(*UpdateProviderScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_DeleteProviderSchedule_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteProviderScheduleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).DeleteProviderSchedule(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/DeleteProviderSchedule",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).DeleteProviderSchedule(ctx, req.(*DeleteProviderScheduleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_CreateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).CreateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/CreateSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).CreateSlot(ctx, req.(*CreateSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_UpdateSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).UpdateSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/UpdateSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).UpdateSlot(ctx, req.(*UpdateSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CalendarService_DeleteSlot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSlotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalendarServiceServer).DeleteSlot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calendar.v1.CalendarService/DeleteSlot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalendarServiceServer).DeleteSlot(ctx, req.(*DeleteSlotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CalendarService_ServiceDesc is the grpc.ServiceDesc for CalendarService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CalendarService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "calendar.v1.CalendarService",
	HandlerType: (*CalendarServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListFreeSlots",
			Handler:    _CalendarService_ListFreeSlots_Handler,
		},
		{
			MethodName: "CreateBooking",
			Handler:    _CalendarService_CreateBooking_Handler,
		},
		{
			MethodName: "GetBooking",
			Handler:    _CalendarService_GetBooking_Handler,
		},
		{
			MethodName: "CancelBooking",
			Handler:    _CalendarService_CancelBooking_Handler,
		},
		{
			MethodName: "ListBookings",
			Handler:    _CalendarService_ListBookings_Handler,
		},
		{
			MethodName: "ListProviderSchedules",
			Handler:    _CalendarService_ListProviderSchedules_Handler,
		},
		{
			MethodName: "CreateProviderSchedule",
			Handler:    _CalendarService_CreateProviderSchedule_Handler,
		},
		{
			MethodName: "UpdateProviderSchedule",
			Handler:    _CalendarService_UpdateProviderSchedule_Handler,
		},
		{
			MethodName: "DeleteProviderSchedule",
			Handler:    _CalendarService_DeleteProviderSchedule_Handler,
		},
		{
			MethodName: "CreateSlot",
			Handler:    _CalendarService_CreateSlot_Handler,
		},
		{
			MethodName: "UpdateSlot",
			Handler:    _CalendarService_UpdateSlot_Handler,
		},
		{
			MethodName: "DeleteSlot",
			Handler:    _CalendarService_DeleteSlot_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/api/calendar/v1/calendar.proto",
}
